import type { ParkingLot } from "../types";
import type { CityConfig } from "./types";

/** Coimbatore pilot (original Slotify prototype). All occupancy data is SIMULATED. */

const lots: ParkingLot[] = [
  {
    id: "brookefields",
    name: "Brookefields Mall Parking",
    area: "Brookefields",
    address: "Krishnasamy Rd, Brookefields, Coimbatore 641001",
    lat: 11.0089, lng: 76.9608,
    category: "mall", layout: { rows: 6, cols: 10 },
    pricePerHour: 40, evSurchargePerHour: 20, baseOccupancy: 0.72,
    openHours: "9:00 – 23:00", features: ["Covered", "EV charging", "CCTV", "Valet"],
    ownerId: "own-kovai-malls", covered: true,
  },
  {
    id: "gandhipuram",
    name: "Gandhipuram Multi-level",
    area: "Gandhipuram",
    address: "Near Central Bus Stand, Gandhipuram, Coimbatore 641012",
    lat: 11.0183, lng: 76.9674,
    category: "transit", layout: { rows: 5, cols: 10 },
    pricePerHour: 25, evSurchargePerHour: 15, baseOccupancy: 0.86,
    openHours: "24 hours", features: ["24×7", "CCTV", "Two-wheeler bays"],
    ownerId: "own-ccmc", covered: true,
  },
  {
    id: "rs-puram",
    name: "RS Puram DB Road Smart Bays",
    area: "RS Puram",
    address: "DB Road, RS Puram, Coimbatore 641002",
    lat: 11.0086, lng: 76.9499,
    category: "commercial", layout: { rows: 4, cols: 8 },
    pricePerHour: 30, evSurchargePerHour: 15, baseOccupancy: 0.64,
    openHours: "8:00 – 22:00", features: ["On-street", "Sensor bays", "Pay by FASTag"],
    ownerId: "own-ccmc", covered: false,
  },
  {
    id: "race-course",
    name: "Race Course Walkers' Parking",
    area: "Race Course",
    address: "Race Course Rd, Coimbatore 641018",
    lat: 10.9992, lng: 76.978,
    category: "commercial", layout: { rows: 4, cols: 10 },
    pricePerHour: 20, evSurchargePerHour: 10, baseOccupancy: 0.41,
    openHours: "5:00 – 22:00", features: ["Open air", "CCTV", "Accessible bays"],
    ownerId: "own-ccmc", covered: false,
  },
  {
    id: "town-hall",
    name: "Town Hall Heritage Parking",
    area: "Town Hall",
    address: "Big Bazaar St, Town Hall, Coimbatore 641001",
    lat: 10.9945, lng: 76.9614,
    category: "commercial", layout: { rows: 4, cols: 8 },
    pricePerHour: 30, evSurchargePerHour: 15, baseOccupancy: 0.91,
    openHours: "8:00 – 21:00", features: ["Near markets", "Two-wheeler bays"],
    ownerId: "own-ccmc", covered: false,
  },
  {
    id: "junction",
    name: "Coimbatore Junction Railway Parking",
    area: "Railway Station",
    address: "State Bank Rd, Gopalapuram, Coimbatore 641018",
    lat: 10.9965, lng: 76.9669,
    category: "transit", layout: { rows: 6, cols: 10 },
    pricePerHour: 20, evSurchargePerHour: 10, baseOccupancy: 0.78,
    openHours: "24 hours", features: ["24×7", "Long stay", "CCTV"],
    ownerId: "own-railways", covered: false,
  },
  {
    id: "psg-peelamedu",
    name: "Peelamedu Tech Park Parking",
    area: "Peelamedu",
    address: "Avinashi Rd, Peelamedu, Coimbatore 641004",
    lat: 11.0247, lng: 77.0028,
    category: "office", layout: { rows: 5, cols: 10 },
    pricePerHour: 30, evSurchargePerHour: 15, baseOccupancy: 0.58,
    openHours: "7:00 – 23:00", features: ["EV charging", "Covered", "Monthly passes"],
    ownerId: "own-kovai-malls", covered: true,
  },
  {
    id: "prozone",
    name: "Prozone Mall Parking",
    area: "Saravanampatti",
    address: "Sathy Rd, Saravanampatti, Coimbatore 641035",
    lat: 11.0557, lng: 76.9947,
    category: "mall", layout: { rows: 6, cols: 10 },
    pricePerHour: 40, evSurchargePerHour: 20, baseOccupancy: 0.49,
    openHours: "10:00 – 23:00", features: ["Covered", "EV charging", "Family bays"],
    ownerId: "own-kovai-malls", covered: true,
  },
  {
    id: "kmch",
    name: "KMCH Hospital Visitor Parking",
    area: "Avinashi Road",
    address: "Avanashi Rd, Civil Aerodrome Post, Coimbatore 641014",
    lat: 11.0418, lng: 77.0402,
    category: "hospital", layout: { rows: 5, cols: 8 },
    pricePerHour: 20, evSurchargePerHour: 10, baseOccupancy: 0.82,
    openHours: "24 hours", features: ["24×7", "Accessible bays", "Drop-off zone"],
    ownerId: "own-kmch", covered: true,
  },
];

export const COIMBATORE: CityConfig = {
  id: "coimbatore",
  name: "Coimbatore",
  shortName: "Coimbatore",
  state: "Tamil Nadu",
  center: { lat: 11.0168, lng: 76.9558 },
  zoom: 13,
  authority: "Coimbatore City Municipal Corporation",
  authorityShort: "CCMC",
  police: "Coimbatore City Traffic Police",
  demoOwnerId: "own-kovai-malls",
  demoOwnerName: "Kovai Malls Parking Co.",
  demoVehicle: "TN38AB1234",
  walletBank: "Kovai Co-op Bank FASTag (demo)",
  plateDistricts: ["37", "38", "39", "40", "41", "66", "99", "02", "09"],
  avgSpeedKmh: 22,
  lots,
  commandZones: [
    {
      id: "z-central", name: "Central", division: "Traffic Central", color: "#d95926",
      localities: [
        { id: "l-gandhipuram", name: "Gandhipuram", lat: 11.0178, lng: 76.9656, kind: "transit", lotIds: ["gandhipuram"], anprCameras: 6, vehiclesPerHour: 2140 },
        { id: "l-townhall", name: "Town Hall & Big Bazaar", lat: 10.9948, lng: 76.9605, kind: "market", lotIds: ["town-hall"], anprCameras: 5, vehiclesPerHour: 1860 },
        { id: "l-junction", name: "Railway Junction", lat: 10.9968, lng: 76.9672, kind: "transit", lotIds: ["junction"], anprCameras: 4, vehiclesPerHour: 1420 },
        { id: "l-rspuram", name: "RS Puram", lat: 11.0082, lng: 76.9496, kind: "market", lotIds: ["rs-puram"], anprCameras: 3, vehiclesPerHour: 980 },
        { id: "l-brookefields", name: "Brookefields", lat: 11.0092, lng: 76.9612, kind: "mall", lotIds: ["brookefields"], anprCameras: 3, vehiclesPerHour: 1110 },
      ],
    },
    {
      id: "z-east", name: "East", division: "Traffic East", color: "#199e70",
      localities: [
        { id: "l-peelamedu", name: "Peelamedu & Avinashi Rd", lat: 11.0253, lng: 77.0031, kind: "it_corridor", lotIds: ["psg-peelamedu", "kmch"], anprCameras: 4, vehiclesPerHour: 1290 },
        { id: "l-racecourse", name: "Race Course", lat: 10.9995, lng: 76.9775, kind: "civic", lotIds: ["race-course"], anprCameras: 2, vehiclesPerHour: 520 },
      ],
    },
    {
      id: "z-north", name: "North", division: "Traffic North", color: "#3987e5",
      localities: [
        { id: "l-saravanampatti", name: "Saravanampatti", lat: 11.0561, lng: 76.9951, kind: "it_corridor", lotIds: ["prozone"], anprCameras: 3, vehiclesPerHour: 640 },
        { id: "l-saibaba", name: "Saibaba Colony", lat: 11.0241, lng: 76.9446, kind: "residential", lotIds: [], anprCameras: 2, vehiclesPerHour: 470 },
      ],
    },
  ],
  violationSpots: [
  { location: "Cross Cut Rd, Gandhipuram", lat: 11.0167, lng: 76.9636 },
  { location: "Oppanakara St, Town Hall", lat: 10.9951, lng: 76.9588 },
  { location: "Big Bazaar St", lat: 10.9938, lng: 76.9632 },
  { location: "100 Feet Rd, Gandhipuram", lat: 11.0209, lng: 76.9611 },
  { location: "Avinashi Rd, Lakshmi Mills", lat: 11.0104, lng: 76.9858 },
  { location: "DB Rd, RS Puram", lat: 11.0092, lng: 76.9514 },
  { location: "Trichy Rd, Ramanathapuram", lat: 10.9951, lng: 76.9926 },
  { location: "Mettupalayam Rd, Saibaba Colony", lat: 11.0245, lng: 76.9451 },
  { location: "Nanjappa Rd, near Bus Stand", lat: 11.0149, lng: 76.9697 },
  { location: "Raja St, Town Hall", lat: 10.9962, lng: 76.9571 },
  { location: "Sathy Rd, Ganapathy", lat: 11.0362, lng: 76.9788 },
  { location: "Race Course Rd, near Collectorate", lat: 11.0007, lng: 76.9741 },
],
  units: [
    { id: "U-CB-01", name: "Patrol C-01 (Gandhipuram)", zoneId: "z-central", kind: "patrol" },
    { id: "U-CB-T1", name: "Tow Truck TW-1 (Central)", zoneId: "z-central", kind: "tow" },
    { id: "U-CB-W1", name: "Warden Team W-1 (Town Hall)", zoneId: "z-central", kind: "warden" },
    { id: "U-CB-04", name: "Patrol E-04 (Avinashi Rd)", zoneId: "z-east", kind: "patrol" },
    { id: "U-CB-06", name: "Patrol N-06 (Saravanampatti)", zoneId: "z-north", kind: "patrol" },
  ],
  vmsBoards: [
    { id: "VMS-CB-01", name: "100 Feet Rd VMS", lat: 11.0215, lng: 76.9610, zoneId: "z-central" },
    { id: "VMS-CB-02", name: "Avinashi Rd VMS", lat: 11.0120, lng: 76.9900, zoneId: "z-east" },
  ],
};
